#!/bin/bash

source ./env_vars

path_to_iso=$1

while [ ! -d "/var/lib/docker/volumes/${user}-Tests" ]; do
    sleep 3
done

mkdir -p /var/lib/docker/volumes/"${user}"-Tests/_data/ubuntu

cp -b -r ../ /var/lib/docker/volumes/"${user}"-Tests/_data/ubuntu/
cp -b $path_to_iso /var/lib/docker/volumes/"${user}"-Assets/_data/iso/
chown -R 496:nogroup /var/lib/docker/volumes/"${user}"-Tests/_data/ubuntu/products/ubuntu/needles
chmod -R 777 /var/lib/docker/volumes/"${user}"-Assets/_data/
# ./fifloader.py -w ../templates.fif.json --filename /var/lib/docker/volumes/"${user}"-Tests/_data/ubuntu/templates
