#!/bin/bash

source ./env_vars

path_to_iso=$1

while [ ! -d "/var/lib/docker/volumes/${user}-Tests" ]; do
    echo waiting for docker volume to be available
    sleep 1
done

echo Copying resources
BASE_FOLDER=/var/lib/docker/volumes/"${user}"-Tests/_data/ubuntu/
mkdir -p $BASE_FOLDER

cp -b -r ../ $BASE_FOLDER
echo Copying $path_to_iso
cp -b $path_to_iso /var/lib/docker/volumes/"${user}"-Assets/_data/iso/
chown -R 496:nogroup /var/lib/docker/volumes/"${user}"-Tests/_data/ubuntu/products/ubuntu/needles
chmod -R 777 /var/lib/docker/volumes/"${user}"-Assets/_data/
echo Loading templates
./fifloader.py -w ../templates.fif.json --filename /var/lib/docker/volumes/"${user}"-Tests/_data/ubuntu/templates
# ../fifloader.py --no-validate -w ../templates.fif.json --filename /var/lib/docker/volumes/"${user}"-Tests/_data/ubuntu/templates
