#!/bin/bash

# user="generic"
source ./env_vars

# Start the openQA Web Interface
docker run -d --name $user-openqa_webui \
    -p $webport:80 -p $rsyncport:873 -p $sslport:443 \
    -v $user-Assets:/var/lib/openqa/share/factory -v $user-Tests:/var/lib/openqa/share/tests \
    binarysequence/openqa-webui
# Generate fake key authentication
while true; do
    curl --fail-with-body -X POST http://localhost:$webport/login > /dev/null 2>&1
    if [[ $? -eq 0 ]]; then
        break
    fi
    echo Failed to generate fake key authentication. Retrying.
    sleep 1
done
# Start one worker
docker run -d --privileged --name $user-openqa_worker \
              --link $user-openqa_webui:openqa-webui \
              --volumes-from $user-openqa_webui \
              localbuntu/worker-x86_64
