#!/bin/bash

# user="generic"
source ./env_vars

# Start the openQA Web Interface
docker run -d --name $user-openqa_webui \
    -p $webport:80 -p $rsyncport:873 -p $sslport:443 \
    -v $user-Assets:/var/lib/openqa/share/factory -v $user-Tests:/var/lib/openqa/share/tests \
    binarysequence/openqa-webui

# Generate fake key authentication
sleep 5; curl -X POST http://localhost:$webport/login

# Start one worker
docker run -d --privileged --name $user-openqa_worker \
              --link $user-openqa_webui:openqa-webui \
              --volumes-from $user-openqa_webui \
              binarysequence/openqa-worker-x86_64
