#!/bin/bash

source ./env_vars

# release=$1
# flavor=$2
# arch=$3


# sudo docker exec "${user}"-openqa_worker openqa-client --host http://openqa-webui isos post DISTRI=ubuntu VERSION="${release}" FLAVOR="${flavor}" ARCH="${arch}"
sudo docker exec "${user}"-openqa_worker openqa-client --host http://openqa-webui isos post DISTRI=ubuntu VERSION=23.04 FLAVOR=desktop ARCH=amd64
